server:
  port: 8123
  pathPrefix: /api/v1
  cors:
    enable: false
    origins:
      - http://localhost:3002
      - http://localhost:5173
db:
  host: postgres
  user: postgres
  password: fyang
  database: todalist_app
  port: 5432
  autoMigration: false
auth:
  whiteList:
    - /api/v1/sys/authentication/passwordLogin
  jwt:
    jwtExpireSec: 94608000 # three years
    jwtIssuer: github.com/todalist/app
    jwtSecret: TN3zIUZjVV0hXe!ya$rvSR2pTeWmcT$HWcwqZasjM^&VjgRaY6fMXGM0KkyPPMX5
# redis:
#   host: redis
#   port: 6379
#   db: 4
